version: 0.2
env:
  parameter-store:
    SERVER_PORT: "SERVER_PORT"
    SERVER_SECRET: "SERVER_SECRET"
    SPRING_DATASOURCE_PASSWORD: "SPRING_DATASOURCE_PASSWORD"
    SPRING_DATASOURCE_URL: "SPRING_DATASOURCE_URL"
    SPRING_DATASOURCE_USERNAME: "SPRING_DATASOURCE_USERNAME"
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo In the pre_build phase...
      - mvn test
  build:
    commands:
      - echo Build completed on `date`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `data`
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
